#!/bin/sh

echo -e "\033[1;31;42m Begin ifconfig-eth0 \e[0m" >>/dev/ttySAC2

# echo "Try to bring eth0 interface up ... ">/dev/ttySAC2

/sbin/ifconfig lo 127.0.0.1

if [ -f /etc/eth0-setting ]; then
	source /etc/eth0-setting
	# if grep -q nfs /proc/mounts ; then  # 支持 nfs 挂载
	if grep -q "^/dev/root / nfs " /etc/mtab; then
		echo "if ------------ /etc/eth0-setting" >>/dev/ttySAC2
		echo -n NFS root ... >>/dev/ttySAC2
	else
		echo "else ------------ /etc/eth0-setting" >>/dev/ttySAC2
		/sbin/ifconfig eth0 down
		/sbin/ifconfig eth0 add $IP
		/sbin/ifconfig eth0 netmask $Mask
		/sbin/ifconfig eth0 broadcast $Broadcast
		/sbin/ifconfig eth0 hw ether $MAC
		route add default gw $Gateway
	fi
	# echo nameserver $DNS >> /etc/resolv.conf
	# echo udhcpc >> /etc/resolv.conf
else
	if grep -q "^/dev/root / nfs " /etc/mtab; then
		echo "if ------------" >>/dev/ttySAC2
		echo -n NFS root ... >>/dev/ttySAC2
	else
		echo "else ------------" >>/dev/ttySAC2
		/sbin/ifconfig eth0 down
		/sbin/ifconfig eth0 add 192.168.1.111
		/sbin/ifconfig eth0 netmask 255.255.255.0
		# /sbin/ifconfig eth0 broadcast 192.168.1.255
		/sbin/ifconfig eth0 hw ether 40:50:60:70:80:90
		route add default gw 192.168.1.1
	fi
fi

/sbin/ifconfig eth0 up
# sleep 1 # 1s
# usleep 10000 # 10ms
# udhcpc

echo -e "\033[1;31;42m End ifconfig-eth0 \e[0m" >>/dev/ttySAC2

exit 0 
